"""Generate the sudoers file for the ``diagbot`` user at bootstrap.

Only exact read-only command templates get a NOPASSWD sudo grant. The generated
file is hashed; the hash is recorded so later drift (an operator relaxing rules)
is detected and alerted on.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from .allowlist import AllowPolicy, AllowRule


def _secure_args(rule: AllowRule) -> str:
    return " " + " ".join(rule.args) if rule.args else ""


def render_sudoers(user: str, policy: AllowPolicy) -> str:
    lines = []
    lines.append("# GENERATED BY harness -- DO NOT EDIT MANUALLY")
    lines.append("# Force no write: only read-only allowlist templates below.")
    lines.append(f"Defaults:{user} !requiretty")
    lines.append("")
    for rule in policy.rules():
        lines.append(f"{user} ALL=(ALL) NOPASSWD: {rule.program}{_secure_args(rule)}")
    lines.append("")
    return "\n".join(lines)


@dataclass(frozen=True)
class SudoersArtifact:
    content: str
    sha256: str


def build(allow_policy_path: str, user: str) -> SudoersArtifact:
    # In a real deployment the policy is loaded from config; here we render the
    # default policy so the scaffold is self-contained. The sha is what is recorded.
    from .allowlist import default_policy
    content = render_sudoers(user, default_policy())
    return SudoersArtifact(content=content, sha256=hashlib.sha256(content.encode()).hexdigest())